spring.config.import=liquibase.properties

spring.jpa.hibernate.ddl-auto=none

spring.datasource.url=jdbc:postgresql://localhost:5432/shop_db?useUnicode=true&characterEncoding=UTF-8\
  &serverTimezone=Asia/Yekaterinburg
spring.jpa.database=postgresql
spring.datasource.username=postgres
spring.datasource.password=d58gt6
spring.datasource.driver-class-name=org.postgresql.Driver

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

spring.jpa.properties.hibernate.format_sql=true
